# TODO support not only Fedora
- name: Include distro-specific vars
  include_vars: '{{ ansible_distribution | lower }}.yml'
- name: Include distro-specific tasks
  include_tasks: '{{ ansible_distribution | lower }}.yml'
