---
- block:
  - name: Remove VK messenger
    package:
      name: vk
      state: absent
    become: true

  - meta: end_play
  when: vk_remove|bool

- fail:
    msg: '{{ ansible_pkg_mgr }} is not supported by VK messenger'
  when: ansible_pkg_mgr not in ['yum', 'dnf', 'zypper']

- name: Install auxiliary packages
  package:
    name:
      - /usr/bin/xmllint
      - wget
  become: true

- name: Find out the latest version of VK messenger
  shell: >
    wget --output-document=- --quiet {{ vk_dlurl }} |
    xmllint 2>/dev/null --html --xpath '//a[contains(@href, "{{ ansible_architecture }}")][last()]' - |
    wget --base={{ vk_dlurl }} --force-html --input-file=- --no-verbose --spider
  changed_when: false
  failed_when: vk_pkg_query_r.stderr == 'No URLs found in -.'
  register: vk_pkg_query_r

- name: Install VK messenger
  package:
    name: "{{ (vk_pkg_query_r.stderr_lines[-1]).split(' ')[3] }}"
  become: true
