---
- block:
  - name: Remove VK messenger
    package:
      name: vk
      state: absent
    become: true

  - meta: end_play
  when: remove|bool

- fail:
    msg: '{{ ansible_pkg_mgr }} is not supported by VK messenger'
  when: ansible_pkg_mgr not in ['yum', 'dnf', 'zypper']

- block:
  - name: 'Install VK messenger {{ vk_version }}'
    package:
      name: '{{ vk_pkg_url }}'

  # Sometimes there's newer version in a repo
  - name: Update VK messenger to the latest version
    package:
      name: vk
      state: latest
  become: true
