---
- block:
  - name: Install pangox-compat
    package:
      name: pangox-compat
      releasever: '32'
    when:
      - not anydesk_remove|bool
      - ansible_distribution == 'Fedora'
      - 33 <= ansible_distribution_major_version|int <= 35

  - name: '{{ anydesk_remove|bool | ternary("Remove", "Add") }} {{ anydesk_repo.description | default(anydesk_package) }} repo'
    yum_repository:
      name: '{{ anydesk_repo.name | default(anydesk_package) }}'
      description: '{{ anydesk_repo.description }}'
      baseurl: '{{ anydesk_repo.repo[ansible_pkg_mgr] }}'
      gpgcheck: true
      gpgkey: '{{ anydesk_repo.gpgkey }}'
      state: '{{ anydesk_remove|bool | ternary("absent", "present") }}'

  - block:
    - name: '{{ anydesk_remove|bool | ternary("Remove", "Install") }} {{ anydesk_package }}'
      package:
        name: '{{ anydesk_package }}'
        state: '{{ anydesk_remove|bool | ternary("absent", "present") }}'
        update_cache: true
    rescue:
      - block:
        - name: A dirty hack prereqs.
          rpm_key:
            key: '{{ anydesk_repo.gpgkey }}'

        - block:
          - name: A dirty hack itself
            package:
              name: 'http://rpm.anydesk.com/centos/{{ ansible_architecture }}/Packages/anydesk-{{ anydesk_known_good_version }}.{{ ansible_architecture }}.rpm'
              disable_gpg_check: true
          rescue:
          - name: A dirtier one when all else fails
            command: 'rpm -ihv --noverify http://rpm.anydesk.com/centos/{{ ansible_architecture }}/Packages/anydesk-{{ anydesk_known_good_version }}.{{ ansible_architecture }}.rpm'
        when: not anydesk_remove|bool

  - name: 'Disable {{ anydesk_service }} service'
    service:
      name: '{{ anydesk_service }}'
      state: stopped
      enabled: false
    when:
      - anydesk_disable_service|bool
      - not anydesk_remove|bool
  become: true
