- block:
  - name: Install pangox-compat
    package:
      name: pangox-compat
      releasever: '32'
    when: ansible_distribution == 'Fedora' and 33 <= ansible_distribution_major_version|int <= 34 and not remove|bool
  - name: '{{ remove|bool | ternary("Remove", "Add") }} {{ repo.description | default(package) }} repo'
    yum_repository:
      name: '{{ repo.name | default(package) }}'
      description: '{{ repo.description }}'
      baseurl: '{{ repo.repo[ansible_pkg_mgr] }}'
      gpgcheck: yes
      gpgkey: '{{ repo.gpgkey }}'
      state: '{{ remove|bool | ternary("absent", "present") }}'
  - name: '{{ remove|bool | ternary("Remove", "Install") }} {{ package }}'
    package:
      name: '{{ package }}'
      state: '{{ remove|bool | ternary("absent", "present") }}'
      update_cache: yes
  become: '{{ not got_root }}'
