---
# TODO support not only Fedora
# Distro-specific vars inclusion is better be done inside distro-specific tasks, not before them
# - name: Include distro-specific vars
#   include_vars: '{{ ansible_distribution | lower }}.yml'
- name: Include distro-specific tasks
  include_tasks: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution | lower }}.yml'
        - empty.yml

- block:
  - name: 'Disable {{ anydesk_service }} autostart'
    file:
      path: '{{ item }}'
      state: absent
    loop: '{{ anydesk_autostart_files }}'
    when: anydesk_disable_autostart|bool

  - name: 'Disable {{ anydesk_service }} service'
    service:
      name: '{{ anydesk_service }}'
      state: stopped
      enabled: false
    when: anydesk_disable_service|bool
  when: not anydesk_remove|bool
  become: true
