---
# TODO gracefully fail on non-amd64 arches
# TODO support not only Fedora
- include_tasks: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution | lower }}.yml'
        - empty.yml
