---
- block:
  - name: '{{ teams_remove|bool | ternary("Remove", "Add") }} {{ teams_repo.description | default(teams_package) }} repo'
    yum_repository:
      name: '{{ teams_repo.name | default(teams_package) }}'
      description: '{{ teams_repo.description | default(teams_package) }}'
      baseurl: '{{ teams_repo.repo[ansible_pkg_mgr] }}'
      gpgcheck: true
      gpgkey: '{{ teams_repo.gpgkey }}'
      state: '{{ teams_remove|bool | ternary("absent", "present") }}'
  - name: '{{ teams_remove|bool | ternary("Remove", "Install") }} {{ teams_package }}'
    package:
      name: '{{ teams_package }}'
      state: '{{ teams_remove|bool | ternary("absent", "latest") }}'
  become: true
