---
# TODO support not only Fedora
- name: Include distro-specific tasks
  include_tasks: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution | lower }}.yml'
      skip: true
