# TODO install from native packages on supported OSes
- block:
  - name: Extract assistant archive
    unarchive:
      src: '{{ as_urls.archive }}'
      dest: '{{ as_unarchive_dir }}'
      remote_src: yes
    register: as_installation
  when: not remove|bool
- block:
  - name: 'Remove {{ as_dir }}'
    file:
      path: '{{ as_dir }}'
      state: absent
  when: remove|bool
