# TODO support not only Linux
- name: Include system-specific tasks
  include_tasks: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution | lower }}.yml'
        - '{{ ansible_system | lower }}.yml'
      skip: true
- name: '{{ "%s %s %s PATH" % remove|bool | ternary(("Remove", as_main_binary, "from"), ("Add", as_main_binary, "to")) }}'
  file:
    src: '{{ remove|bool | ternary(omit, as_main_binary) }}'
    dest: '{{ as_main_binary }}'
    state: '{{ remove|bool | ternary("absent", "link") }}'
  when: systemwide
