---
# TODO install a specific version
# TODO support not only Linux
- block:
  - name: Uninstall assistant
    package:
      name: assistant
      state: absent
    become: true

  - meta: end_host
  when: remove|bool

- name: Install auxiliary packages
  package:
    name:
      - '{{ assistant_xmllint_pkg[ansible_os_family | lower] | default("/usr/bin/xmllint") }}'
      - wget
  become: true

- name: 'Find out the latest version for {{ ansible_pkg_mgr }}'
  shell: >
    wget --output-document=- --quiet {{ assistant_dlurl }} |
    xmllint 2>/dev/null --html --xpath '(//a[contains(text(), "{{ assistant_pkg_fmt | upper }}")])[1]' - |
    wget --base={{ assistant_baseurl }} --force-html --input-file=- --no-verbose --spider
  changed_when: false
  failed_when: assistant_pkg_query_r.stderr == 'No URLs found in -.'
  register: assistant_pkg_query_r

- name: 'Donwload the latest version for {{ ansible_pkg_mgr }}'
  get_url:
    url: "{{ (assistant_pkg_query_r.stderr_lines[-1]).split(' ')[3] }}"
    dest: /tmp/
  register: assistant_pkg_r

- include_tasks: '{{ item }}'
  with_first_found:
    - 'install-{{ ansible_distribution | lower }}.yml'
    - 'install-{{ ansible_os_family | lower }}.yml'
    - 'install-{{ ansible_system | lower }}.yml'
