---
- block:
  - name: '{{ skype_remove|bool | ternary("Remove", "Add") }} Skype GPG key'
    rpm_key:
      key: https://repo.skype.com/data/SKYPE-GPG-KEY
      state: '{{ skype_remove|bool | ternary("absent", "present") }}'
  - name: '{{ skype_remove|bool | ternary("Remove", "Install latest") }} skype'
    dnf:
      name: '{{ skype_remove|bool | ternary("skype", "https://go.skype.com/skypeforlinux-64.rpm") }}'
      state: '{{ skype_remove|bool | ternary("absent", "present") }}'
    ignore_errors: '{{ skype_remove|bool }}'
    register: skype_latest
  rescue:
  - debug:
      var: skype_latest
  - name: Install known good if latest is non-installable
    dnf:
      name: '{{ skype_stable }}'
    when: not skype_remove|bool
  become: true
