- name: Remove modularity repos
  package:
    name: fedora-repos-modular
    state: absent
- block:
  - name: Install distribution GPG keys
    package:
      name: distribution-gpg-keys
  - name: Add RPM Fusion GPG keys
    rpm_key:
      key: '{{ item }}'
    loop: "{{ query('fileglob', '/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-*{{ ansible_distribution_major_version }}*') }}"
  - name: Add RPM Fusion itself
    package:
      name:
        - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
        - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
  tags:
    - rpmfusion
- name: Add repository GPG keys
  rpm_key:
    key: '{{ item }}'
  loop: '{{ gpgkeys }}'
- name: Add extra repositories
  yum_repository:
    name: '{{ item.name }}'
    description: '{{ item.description | default(item.name) }}'
    baseurl: '{{ item.baseurl | default(omit) }}'
    metalink: '{{ item.metalink | default(omit) }}'
    mirrorlist: '{{ item.mirrorlist | default(omit) }}'
    gpgcheck: '{{ item.gpgkey is defined }}'
    gpgkey: '{{ item.gpgkey | default(omit) }}'
  loop: '{{ extrarepos | default([]) }}'
