- name: Remove modularity repos
  package:
    name: fedora-repos-modular
    state: absent
- include_tasks: rpmfusion.yml
  tags:
    - rpmfusion
- name: Add repository GPG keys
  rpm_key:
    key: '{{ item }}'
  loop: '{{ gpgkeys }}'
- name: Add extra repositories
  yum_repository:
    name: '{{ item.name }}'
    description: '{{ item.description | default(item.name) }}'
    baseurl: '{{ item.baseurl | default(omit) }}'
    metalink: '{{ item.metalink | default(omit) }}'
    mirrorlist: '{{ item.mirrorlist | default(omit) }}'
    gpgcheck: '{{ item.gpgkey is defined }}'
    gpgkey: '{{ item.gpgkey | default(omit) }}'
  loop: '{{ extrarepos | default([]) }}'
