---
- name: Cut the crap (prepare)
  lineinfile:
    name: /etc/dnf/protected.d/fedora-workstation.conf
    line: gnome-shell
    state: absent

- name: Cut the crap (actually)
  package:
    name: '{{ useless_crap | default([]) }}'
    autoremove: false
    state: absent
  when: false

- block:
  - name: Install distribution GPG keys
    package:
      name: distribution-gpg-keys

  - name: Add RPM Fusion GPG keys
    rpm_key:
      key: '{{ gpg_key }}'
    loop: "{{ query('fileglob', '/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-*{{ ansible_distribution_major_version }}*') }}"
    loop_control:
      loop_var: gpg_key

  - name: Add RPM Fusion itself
    package:
      name:
        - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
        - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

  - name: Add packages from RPM Fusion
    package:
      name: '{{ pkgs }}'
      state: latest
      enablerepo: '{{ repos2enable | default(omit) }}'
      update_cache: true
  tags:
    - rpmfusion

- name: Add repository GPG keys
  rpm_key:
    key: '{{ gpg_key }}'
  loop: '{{ gpgkeys | default([]) }}'
  loop_control:
    loop_var: gpg_key

- name: Add extra repositories
  yum_repository:
    name: '{{ repo.name }}'
    description: '{{ repo.description | default(repo.name) }}'
    baseurl: '{{ repo.baseurl | default(omit) }}'
    metalink: '{{ repo.metalink | default(omit) }}'
    mirrorlist: '{{ repo.mirrorlist | default(omit) }}'
    gpgcheck: '{{ repo.gpgkey is defined }}'
    gpgkey: '{{ repo.gpgkey | default(omit) }}'
  loop: '{{ extrarepos | default([]) }}'
  loop_control:
    loop_var: repo
