# TODO support not only Fedora
- name: Include distro-specific vars
  include_vars: '{{ ansible_distribution | lower }}.yml'
- block:
  - name: Include distro-specific tasks
    include_tasks: '{{ ansible_distribution | lower }}.yml'
  - name: Add extra repositories (via package manager)
    package:
      name: '{{ repopkgs | default([]) }}'
  - package:
      name: '{{ pkgs }}'
      state: latest
      enablerepo: '{{ repos2enable | default(omit) }}'
  - package:
      name: '{{ extrapkgs | default([]) }}'
  become: '{{ not got_root }}'
# Employer-specific tasks (if any)
- include_tasks: '{{ item }}'
  loop: '{{ query("fileglob", "emp/*.yml") }}'
- block:
  - name: Make room for git repos
    file:
      name: '{{ projects_dir }}'
      state: directory
  - name: Clone remote git repos
    git:
      repo: '{{ item }}'
      dest: '{{ projects_dir }}/{{ (item | basename | splitext)[0] }}'
      accept_hostkey: yes
      # setting update to yes overwrites local unpushed commits
      update: no
    loop: '{{ gitrepos }}'
  tags:
    - gitrepos
